---
abstract: 'for App::CLI::Extension easy Log::Dispatch module'
author:
  - 'Akira Horimoto <kurt0027@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.30
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-CLI-Plugin-Log-Dispatch-Configurator-YAML
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  App::CLI::Extension: 1.2
  Log::Dispatch::Config: 0
  Log::Dispatch::Configurator::YAML: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.0
